//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DB {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DB() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Properties.DB", typeof(DB).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при создании подключения к БД.
        /// </summary>
        public static string Connection_create_error {
            get {
                return ResourceManager.GetString("Connection_create_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заданный файл БД отсутствует.
        /// </summary>
        public static string File_absent {
            get {
                return ResourceManager.GetString("File_absent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не задано имя файла с БД.
        /// </summary>
        public static string No_filename {
            get {
                return ResourceManager.GetString("No_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.Jet.OLEDB.4.0.
        /// </summary>
        public static string Provider0 {
            get {
                return ResourceManager.GetString("Provider0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.ACE.OLEDB.12.0.
        /// </summary>
        public static string Provider1 {
            get {
                return ResourceManager.GetString("Provider1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.ACE.OLEDB.14.0.
        /// </summary>
        public static string Provider2 {
            get {
                return ResourceManager.GetString("Provider2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.ACE.OLEDB.16.0.
        /// </summary>
        public static string Provider3 {
            get {
                return ResourceManager.GetString("Provider3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не обнаружены провайдеры подключения к БД.
        /// </summary>
        public static string Providers_error {
            get {
                return ResourceManager.GetString("Providers_error", resourceCulture);
            }
        }
    }
}
