//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RegEx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegEx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Properties.RegEx", typeof(RegEx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^([4-9]|1\d|20)?$.
        /// </summary>
        public static string AB {
            get {
                return ResourceManager.GetString("AB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^.
        /// </summary>
        public static string Begin {
            get {
                return ResourceManager.GetString("Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(0?[,.][5-9]|[1-9]([,.]\d?)?|[1-2]\d([,.]\d?)?|30([,.]0?)?)?$.
        /// </summary>
        public static string Depth {
            get {
                return ResourceManager.GetString("Depth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \d+.
        /// </summary>
        public static string DigitInString {
            get {
                return ResourceManager.GetString("DigitInString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^([1-9]|1[0-4])?$.
        /// </summary>
        public static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^$.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^([1-{0}]\d([,.]\d?)?|{1}0([,.]0?)?)$.
        /// </summary>
        public static string Format_end0 {
            get {
                return ResourceManager.GetString("Format_end0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^([1-{0}]\d([,.]\d?)?|{1}[0-4]([,.]\d?)?|{1}5([,.]0?)?)$.
        /// </summary>
        public static string Format_end5 {
            get {
                return ResourceManager.GetString("Format_end5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(0?[,.][5-9]|[1-9]([,.]\d?)?|1[0-1]([,.]\d?)?|12([,.]0?)?)?$.
        /// </summary>
        public static string Thickness {
            get {
                return ResourceManager.GetString("Thickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(\d([,.]\d?)?|[,.]\d)?$.
        /// </summary>
        public static string Values_0__9_9 {
            get {
                return ResourceManager.GetString("Values_0__9_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^([1-9]|[1-9]\d|100)?$.
        /// </summary>
        public static string Values_1_100 {
            get {
                return ResourceManager.GetString("Values_1_100", resourceCulture);
            }
        }
    }
}
