//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ToolTips {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ToolTips() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Properties.ToolTips", typeof(ToolTips).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ширина поля.
        /// </summary>
        public static string A {
            get {
                return ResourceManager.GetString("A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Допустимые значения параметра [4-20].
        /// </summary>
        public static string AB_wrong {
            get {
                return ResourceManager.GetString("AB_wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Высота поля.
        /// </summary>
        public static string B {
            get {
                return ResourceManager.GetString("B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мощность.
        /// </summary>
        public static string Device_Power {
            get {
                return ResourceManager.GetString("Device_Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расстояние источник-центр вращения аппарата.
        /// </summary>
        public static string Device_SCD {
            get {
                return ResourceManager.GetString("Device_SCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение коэффициента Кб.
        /// </summary>
        public static string Kb {
            get {
                return ResourceManager.GetString("Kb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значние коэффициента L.
        /// </summary>
        public static string Lung {
            get {
                return ResourceManager.GetString("Lung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расстояние от точки расчета до легкого (не более).
        /// </summary>
        public static string Lung_Distance {
            get {
                return ResourceManager.GetString("Lung_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Допустимые значения параметра [1-14].
        /// </summary>
        public static string Lung_Distance_wrong {
            get {
                return ResourceManager.GetString("Lung_Distance_wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Толщина легочной ткани.
        /// </summary>
        public static string Lung_Thickness {
            get {
                return ResourceManager.GetString("Lung_Thickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Допустимые значения параметра [0.5-12.0].
        /// </summary>
        public static string Lung_Thickness_wrong {
            get {
                return ResourceManager.GetString("Lung_Thickness_wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение коэффициента ОТВ.
        /// </summary>
        public static string OTV {
            get {
                return ResourceManager.GetString("OTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Глубина.
        /// </summary>
        public static string OTV_Depth {
            get {
                return ResourceManager.GetString("OTV_Depth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Допустимые значения параметра [0.5-30.0].
        /// </summary>
        public static string OTV_Depth_wrong {
            get {
                return ResourceManager.GetString("OTV_Depth_wrong", resourceCulture);
            }
        }
    }
}
