//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ToolTips {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ToolTips() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Properties.ToolTips", typeof(ToolTips).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ширина поля.
        /// </summary>
        public static string A {
            get {
                return ResourceManager.GetString("A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Допустимые значения параметра [4-20].
        /// </summary>
        public static string AB_wrong {
            get {
                return ResourceManager.GetString("AB_wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Высота поля.
        /// </summary>
        public static string B {
            get {
                return ResourceManager.GetString("B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мощность.
        /// </summary>
        public static string Device_Power {
            get {
                return ResourceManager.GetString("Device_Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расстояние источник-центр вращения аппарата.
        /// </summary>
        public static string Device_SCD {
            get {
                return ResourceManager.GetString("Device_SCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение коэффициента Кб.
        /// </summary>
        public static string Kb {
            get {
                return ResourceManager.GetString("Kb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значние коэффициента L.
        /// </summary>
        public static string Lung {
            get {
                return ResourceManager.GetString("Lung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расстояние от точки расчета до легкого (не более).
        /// </summary>
        public static string Lung_Distance {
            get {
                return ResourceManager.GetString("Lung_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Допустимые значения параметра [1-14].
        /// </summary>
        public static string Lung_Distance_wrong {
            get {
                return ResourceManager.GetString("Lung_Distance_wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Толщина легочной ткани.
        /// </summary>
        public static string Lung_Thickness {
            get {
                return ResourceManager.GetString("Lung_Thickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Допустимые значения параметра [0.5-12.0].
        /// </summary>
        public static string Lung_Thickness_wrong {
            get {
                return ResourceManager.GetString("Lung_Thickness_wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение коэффициента ОТВ.
        /// </summary>
        public static string OTV {
            get {
                return ResourceManager.GetString("OTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Глубина.
        /// </summary>
        public static string OTV_Depth {
            get {
                return ResourceManager.GetString("OTV_Depth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Допустимые значения параметра [0.5-30.0].
        /// </summary>
        public static string OTV_Depth_wrong {
            get {
                return ResourceManager.GetString("OTV_Depth_wrong", resourceCulture);
            }
        }
    }
}
