//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorComponents.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CalculatorComponents.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^$|^([4-9]|1\d|20)$.
        /// </summary>
        internal static string RegEx_AB {
            get {
                return ResourceManager.GetString("RegEx_AB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^$|^(0?[,.][5-9]|[1-9]|[1-2]\d|30|[1-9][,.]\d?|[1-2]\d[,.]\d?|30[,.]0?)$.
        /// </summary>
        internal static string RegEx_Depth {
            get {
                return ResourceManager.GetString("RegEx_Depth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^$|^([1-9]|1[0-4])$.
        /// </summary>
        internal static string RegEx_Distance {
            get {
                return ResourceManager.GetString("RegEx_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^$|^(0?[,.][5-9]|[1-9]|1[0-1]|12|[1-9][,.]\d?|1[0-1][,.]\d?|12[,.]0?)$.
        /// </summary>
        internal static string RegEx_Thickness {
            get {
                return ResourceManager.GetString("RegEx_Thickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM [Аппараты];.
        /// </summary>
        internal static string SQL_Device {
            get {
                return ResourceManager.GetString("SQL_Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Кб.Кб FROM Кб WHERE Кб.РИЦ=? AND Кб.A=? AND Кб.B=?;.
        /// </summary>
        internal static string SQL_Kb {
            get {
                return ResourceManager.GetString("SQL_Kb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кб.A.
        /// </summary>
        internal static string SQL_Kb_A {
            get {
                return ResourceManager.GetString("SQL_Kb_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кб.B.
        /// </summary>
        internal static string SQL_Kb_B {
            get {
                return ResourceManager.GetString("SQL_Kb_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кб.РИЦ.
        /// </summary>
        internal static string SQL_Kb_SCD {
            get {
                return ResourceManager.GetString("SQL_Kb_SCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [Легочная ткань].L FROM [Легочная ткань] WHERE [Легочная ткань].[Толщина легкого]=? AND [Легочная ткань].[Расстояние от точки расчета до легкого (не более)]=?;.
        /// </summary>
        internal static string SQL_Lung {
            get {
                return ResourceManager.GetString("SQL_Lung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Легочная ткань].[Расстояние от точки расчета до легкого (не более)].
        /// </summary>
        internal static string SQL_Lung_Distance {
            get {
                return ResourceManager.GetString("SQL_Lung_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Легочная ткань].[Толщина легкого].
        /// </summary>
        internal static string SQL_Lung_Thickness {
            get {
                return ResourceManager.GetString("SQL_Lung_Thickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ОТВ.ОТВ FROM ОТВ WHERE ОТВ.Глубина=? AND ОТВ.B=? AND ОТВ.A=?;.
        /// </summary>
        internal static string SQL_OTV {
            get {
                return ResourceManager.GetString("SQL_OTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОТВ.A.
        /// </summary>
        internal static string SQL_OTV_A {
            get {
                return ResourceManager.GetString("SQL_OTV_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОТВ.B.
        /// </summary>
        internal static string SQL_OTV_B {
            get {
                return ResourceManager.GetString("SQL_OTV_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОТВ.Глубина.
        /// </summary>
        internal static string SQL_OTV_Depth {
            get {
                return ResourceManager.GetString("SQL_OTV_Depth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to минут.
        /// </summary>
        internal static string Time_minutes {
            get {
                return ResourceManager.GetString("Time_minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to секунд.
        /// </summary>
        internal static string Time_seconds {
            get {
                return ResourceManager.GetString("Time_seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мощность.
        /// </summary>
        internal static string ToolTip_Device_Power {
            get {
                return ResourceManager.GetString("ToolTip_Device_Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расстояние источник-центр вращения аппарата.
        /// </summary>
        internal static string ToolTip_Device_SCD {
            get {
                return ResourceManager.GetString("ToolTip_Device_SCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение коэффициента Кб.
        /// </summary>
        internal static string ToolTip_Kb {
            get {
                return ResourceManager.GetString("ToolTip_Kb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ширина поля.
        /// </summary>
        internal static string ToolTip_Kb_A {
            get {
                return ResourceManager.GetString("ToolTip_Kb_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Допустимые значения параметра [4-20].
        /// </summary>
        internal static string ToolTip_Kb_AB_wrong {
            get {
                return ResourceManager.GetString("ToolTip_Kb_AB_wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Высота поля.
        /// </summary>
        internal static string ToolTip_Kb_B {
            get {
                return ResourceManager.GetString("ToolTip_Kb_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значние коэффициента L.
        /// </summary>
        internal static string ToolTip_Lung {
            get {
                return ResourceManager.GetString("ToolTip_Lung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расстояние от точки расчета до легкого (не более).
        /// </summary>
        internal static string ToolTip_Lung_Distance {
            get {
                return ResourceManager.GetString("ToolTip_Lung_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Допустимые значения параметра [1-14].
        /// </summary>
        internal static string ToolTip_Lung_Distance_wrong {
            get {
                return ResourceManager.GetString("ToolTip_Lung_Distance_wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Толщина легочной ткани.
        /// </summary>
        internal static string ToolTip_Lung_Thickness {
            get {
                return ResourceManager.GetString("ToolTip_Lung_Thickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Допустимые значения параметра [0.5-12.0].
        /// </summary>
        internal static string ToolTip_Lung_Thickness_wrong {
            get {
                return ResourceManager.GetString("ToolTip_Lung_Thickness_wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение коэффициента ОТВ.
        /// </summary>
        internal static string ToolTIp_OTV {
            get {
                return ResourceManager.GetString("ToolTIp_OTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Глубина.
        /// </summary>
        internal static string ToolTip_OTV_Depth {
            get {
                return ResourceManager.GetString("ToolTip_OTV_Depth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Допустимые значения параметра [0.5-30.0].
        /// </summary>
        internal static string ToolTip_OTV_Depth_wrong {
            get {
                return ResourceManager.GetString("ToolTip_OTV_Depth_wrong", resourceCulture);
            }
        }
    }
}
