//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanCalculator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlanCalculator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [Аппараты] ([Аппараты].[Аппарат],[Аппараты].[Мощность],[Аппараты].[РИЦ],[Аппараты].[Время в минутах],[Аппараты].[Дата замера мощности]) VALUES(?,?,?,?,?);.
        /// </summary>
        internal static string CreateDeviceSQL {
            get {
                return ResourceManager.GetString("CreateDeviceSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DB {
            get {
                object obj = ResourceManager.GetObject("DB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Аппараты].[Дата замера мощности].
        /// </summary>
        internal static string DeviceCheckPower_Table {
            get {
                return ResourceManager.GetString("DeviceCheckPower_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Аппараты].[Аппарат].
        /// </summary>
        internal static string DeviceName_Table {
            get {
                return ResourceManager.GetString("DeviceName_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Аппараты].[Мощность].
        /// </summary>
        internal static string DevicePower_Table {
            get {
                return ResourceManager.GetString("DevicePower_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Аппараты].[РИЦ].
        /// </summary>
        internal static string DeviceSCD_Table {
            get {
                return ResourceManager.GetString("DeviceSCD_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Аппараты].[Время в минутах].
        /// </summary>
        internal static string DeviceTime_Table {
            get {
                return ResourceManager.GetString("DeviceTime_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \d?|\d[,.]?|\d[,.]\d?|[,.]\d.
        /// </summary>
        internal static string RegEx_0__9_9 {
            get {
                return ResourceManager.GetString("RegEx_0__9_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^.
        /// </summary>
        internal static string RegEx_Begin {
            get {
                return ResourceManager.GetString("RegEx_Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^$.
        /// </summary>
        internal static string RegEx_Empty {
            get {
                return ResourceManager.GetString("RegEx_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        internal static string RegEx_End {
            get {
                return ResourceManager.GetString("RegEx_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [1-{0}]\d[,.]?|[1-{0}]\d[,.]\d?|{1}[,.]?|{1}[,.]0?.
        /// </summary>
        internal static string RegEx_format_end0 {
            get {
                return ResourceManager.GetString("RegEx_format_end0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [1-{0}]\d[,.]?|[1-{0}]\d[,.]\d?|{1}[0-4][,.]?|{1}[0-4][,.]\d?|{2}[,.]?|{2}[,.]0?.
        /// </summary>
        internal static string RegEx_format_end5 {
            get {
                return ResourceManager.GetString("RegEx_format_end5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [Аппараты] SET [Аппараты].[Мощность]=?, [Аппараты].[Дата замера мощности]=? WHERE [Аппараты].[Аппарат]=?;.
        /// </summary>
        internal static string UpdateDeviceSQL {
            get {
                return ResourceManager.GetString("UpdateDeviceSQL", resourceCulture);
            }
        }
    }
}
